[build]
  publish = "public"  # Replace with your output directory for static files
  functions = "functions"  # Specify the directory where your functions are located

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[headers]
  /* = [
    { key = "Access-Control-Allow-Origin", value = "*" },  # Allow CORS for all domains
    { key = "Access-Control-Allow-Headers", value = "Content-Type" },
    { key = "Access-Control-Allow-Methods", value = "GET, POST, OPTIONS" }
  ]

[functions]
  node_bundler = "webpack"  # Choose your preferred bundler (webpack, esbuild, etc.)

# Optional: Configure build environment variables
[build.environment]
  NODE_ENV = "production"  # Example of setting an environment variable

# Optional: Specify how functions should be served
[functions.http]
  maxDuration = 10  # Maximum execution duration for functions in seconds
