[build]
  functions = "functions" # Set the folder where your functions are located
  publish = "public" # Set the folder where your static files are located

[[headers]]
  # This section allows CORS configuration
  for = "/*" # This applies to all routes
    [headers.values]
      Access-Control-Allow-Origin = "https://soaw.samcart.com"
      Access-Control-Allow-Headers = "Content-Type"
      Access-Control-Allow-Methods = "POST, OPTIONS"
      Access-Control-Allow-Credentials = true
